### ISSUE TITLE
Paper Length issue

### ISSUE THREAD

**Issue by elientumba2019** [BritishMachineVisionAssociation/BMVCTemplate#14]
Hello.
BMVC papers are supposed to be 9pages long(references excluded) however most BMVC papers I read are 10 pages long.
could you provide some details on that ?
Thanks

**Comment by elientumba2019** [comment]
[an example paper](https://bmvc2019.org/wp-content/uploads/papers/1103-paper.pdf)

**Comment by FriedRonaldo** [comment]
Hi, I am not related to BMVA, however, I think that the page limit of the final version (10pages) is different from the review version (9pages).

This is the guideline for the review : [bmvc_review.pdf](https://github.com/BritishMachineVisionAssociation/BMVCTemplate/blob/master/bmvc_review.pdf)

And here is for the final : [bmvc_final.pdf](https://github.com/BritishMachineVisionAssociation/BMVCTemplate/blob/master/bmvc_final.pdf)

Therefore, the paper should contain under 9 pages for review.

**Comment by ndfcampbell** [comment]
Hi both,

yes - that is indeed correct - the review version is limited to 9 pages plus references and then an extra page is allowed to incorporate any revisions for the final camera ready version.

Best Wishes,

Neill
