### ISSUE TITLE
Review paper header.

### ISSUE THREAD

**Issue by elientumba2019** [BritishMachineVisionAssociation/BMVCTemplate#16]
Hello. 
When submitting the review paper, do we need to remove this header ?
![header](https://user-images.githubusercontent.com/26796538/122001384-da145280-cde2-11eb-9e2e-6622eb6c0cd2.PNG)
if yes how to remove it ? 
Thank you.

**Comment by elientumba2019** [comment]
Also do we need to included the paper title ?

**Comment by FunkyKoki** [comment]
Same question. Please help.

**Comment by elientumba2019** [comment]
@ndfcampbell hello could you please answer the above question ?

**Comment by ndfcampbell** [comment]
Hi both, When you replace the title with your actual paper title then the header will adjust. The header and the paper title should be included in the review version but the actual author names will not be at this stage since the submitted review paper must be anonymous. Does this make sense? Best Wishes, Neill

**Comment by siahuat0727** [comment]
@ndfcampbell Hi! 
Is it we should manually adjust the header, like changing the line below into
`\runninghead{Student, Prof, Collaborator}{Our title}`?
https://github.com/BritishMachineVisionAssociation/BMVCTemplate/blob/fdf630802f16fc4a4358db8de572f4f0b2d7386e/bmvc_review.tex#L27

![image](https://user-images.githubusercontent.com/17688111/122555096-6be2c080-d06c-11eb-8bf8-98452b16c64c.png)

Thanks!

**Comment by ndfcampbell** [comment]
I see what you mean - feel free to set it to:

\runninghead{Author(s)}{Short Paper Title}

Where "Short Paper Title" can be a shortened version of the full paper title if the paper title is too long to fit in the header. 

Hope that's OK?

**Comment by siahuat0727** [comment]
Thank you!

**Comment by FunkyKoki** [comment]
Thanks for your reply!
