### ISSUE TITLE
Fail to show the complete author list

### ISSUE THREAD

**Issue by wjzzzyx** [BritishMachineVisionAssociation/BMVCTemplate#19]
Hello, I have a paper with a long author list (12) authors. I used \addauthor to add all of them, but only the first 9 are shown in the pdf. Could anyone help about that?

**Comment by HowieMa** [comment]
Same issues. Hope someone can provide solutions.

**Comment by deekshadangwal** [comment]
We're having the same issue as well!

**Comment by ndfcampbell** [comment]
Hi all - sorry about this - seems there was a bug when the count moves into double digits - this should have been fixed now - please let me know if there are any further problems.
